on:
  push:
    branches: 
    - '**'        # matches every branch
    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: generate-sitemap
        # uses: cicirello/generate-sitemap@105142a5bf05423bb574324f566ba3d265001004
        uses: cicirello/generate-sitemap@v1.9.0
